// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
   public static final class Shoulder {
         //
         public static final double P = 2.4f;
         public static final int I = 0;
         public static final double D = 0.1f;
         //
         public static final int P2 = 60;
         public static final int I2 = 0;
         public static final int D2 = 6;
         //
         public static final int PosHigh = 180;
         public static final int PosMedium = 90;
         public static final int PosLow = 0;
         public static final double Buffer = .1f;
         
   }
}


